"use client";

import clsx from "clsx";
import { AlignLeft, Hash, ListChecks, ListTree, NotebookPen, Sparkles } from "lucide-react";
import { memo, type ReactNode } from "react";

import { formatClock } from "@/lib/format";
import type { Chapter, Summary } from "@/lib/types";

function provenance(summary: Summary): string {
  if (summary.generated_by === "llm") return `Generated by ${summary.model ?? "AI"}`;
  if (summary.generated_by === "rules") return "Generated from the transcript";
  return "AI notes";
}

function Section({ icon: Icon, title, children }: { icon: typeof Hash; title: string; children: ReactNode }) {
  return (
    <section className="border-b border-gray-100 px-4 py-5 last:border-b-0 md:px-6">
      <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-gray-900">
        <Icon className="size-4 text-brand-600" />
        {title}
      </h3>
      {children}
    </section>
  );
}

/** Left panel: the AI notes, in the order Fireflies' "General Summary" uses. */
export const NotesPanel = memo(function NotesPanel({
  summary,
  keywords,
  chapters,
  activeChapterIndex,
  onSeek,
  actionItems,
}: {
  summary: Summary | null;
  keywords: string[];
  chapters: Chapter[];
  activeChapterIndex: number;
  onSeek: (ms: number) => void;
  actionItems: ReactNode;
}) {
  return (
    <div className="min-h-0 overflow-y-auto" aria-label="AI notes">
      <div className="flex items-center justify-between border-b border-gray-200 px-4 py-3 md:px-6">
        <h2 className="flex items-center gap-2 font-display text-sm font-semibold text-gray-900">
          <Sparkles className="size-4 text-brand-500" /> AI Notes
        </h2>
        {summary ? (
          <span className="rounded-full bg-brand-50 px-2 py-0.5 text-[11px] font-medium text-brand-700">
            {provenance(summary)}
          </span>
        ) : null}
      </div>

      {keywords.length > 0 ? (
        <Section icon={Hash} title="Keywords">
          <div className="flex flex-wrap gap-1.5">
            {keywords.map((keyword) => (
              <span key={keyword} className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-700">
                {keyword}
              </span>
            ))}
          </div>
        </Section>
      ) : null}

      {summary ? (
        <Section icon={AlignLeft} title="Overview">
          <p className="text-sm leading-6 text-gray-700">{summary.overview}</p>
        </Section>
      ) : null}

      {summary && summary.notes.length > 0 ? (
        <Section icon={NotebookPen} title="Notes">
          <ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-gray-700 marker:text-brand-400">
            {summary.notes.map((note, index) => (
              <li key={index}>{note}</li>
            ))}
          </ul>
        </Section>
      ) : null}

      {chapters.length > 0 ? (
        <Section icon={ListTree} title="Outline">
          <ol className="space-y-1">
            {chapters.map((chapter, index) => (
              <li key={chapter.id}>
                <button
                  type="button"
                  onClick={() => onSeek(chapter.start_ms)}
                  aria-current={index === activeChapterIndex ? "true" : undefined}
                  className={clsx(
                    "flex w-full gap-3 rounded-lg px-2 py-2 text-left transition-colors",
                    index === activeChapterIndex ? "bg-brand-50" : "hover:bg-gray-50",
                  )}
                >
                  <span className="mt-0.5 shrink-0 rounded bg-brand-100 px-1.5 py-0.5 text-[11px] font-semibold tabular-nums text-brand-700">
                    {formatClock(chapter.start_ms)}
                  </span>
                  <span className="min-w-0">
                    <span className="block text-sm font-medium text-gray-900">{chapter.title}</span>
                    {chapter.gist ? <span className="mt-0.5 block text-xs leading-5 text-gray-500">{chapter.gist}</span> : null}
                  </span>
                </button>
              </li>
            ))}
          </ol>
        </Section>
      ) : null}

      <Section icon={ListChecks} title="Action Items">
        {actionItems}
      </Section>
    </div>
  );
});
