"use client";

import clsx from "clsx";
import { Copy, Sparkles } from "lucide-react";
import Link from "next/link";
import { memo, useState, type ReactNode } from "react";
import { toast } from "sonner";

import { AvatarStack } from "@/components/ui/Avatar";
import { Tabs } from "@/components/ui/Tabs";
import { formatDuration, formatMeetingDate } from "@/lib/format";
import type { Chapter, MeetingDetail } from "@/lib/types";

import { TimeLink } from "./TimeLink";

function provenance(meeting: MeetingDetail): string | null {
  const summary = meeting.summary;
  if (!summary) return null;
  if (summary.generated_by === "llm") return `Notes generated by ${summary.model ?? "AI"}`;
  if (summary.generated_by === "rules") return "Notes generated from the transcript";
  return null;
}

function notesAsText(meeting: MeetingDetail): string {
  const lines = [meeting.title, ""];
  if (meeting.summary) lines.push("Overview", meeting.summary.overview, "", "Notes", ...meeting.summary.notes.map((note) => `- ${note}`), "");
  if (meeting.action_items.length) lines.push("Action items", ...meeting.action_items.map((item) => `- ${item.text}`));
  return lines.join("\n");
}

function Heading({ children }: { children: ReactNode }) {
  return <h3 className="mb-2 mt-7 text-[15px] font-medium text-gray-900">{children}</h3>;
}

/** Centre panel: the meeting's AI notes laid out like Fireflies' "General Summary". */
export const NotesPanel = memo(function NotesPanel({
  meeting,
  ownerName,
  activeChapterIndex,
  onSeek,
  actionItems,
}: {
  meeting: MeetingDetail;
  ownerName: string;
  activeChapterIndex: number;
  onSeek: (ms: number) => void;
  actionItems: ReactNode;
}) {
  const [tab, setTab] = useState<"notes" | "skills">("notes");
  const { summary, keywords, chapters } = meeting;
  const source = provenance(meeting);

  return (
    <div className="h-full overflow-y-auto" aria-label="Meeting notes">
      <div className="sticky top-0 z-10 flex justify-center bg-surface/95 py-3 backdrop-blur">
        <Tabs
          label="Notes views"
          value={tab}
          onValueChange={setTab}
          items={[
            { value: "notes", label: "Notes" },
            { value: "skills", label: "AI Skills", badge: 0 },
          ]}
        />
      </div>

      {tab === "skills" ? (
        <div className="mx-auto max-w-md px-6 py-16 text-center">
          <Sparkles className="mx-auto mb-3 size-6 text-brand-500" />
          <p className="font-medium text-gray-900">AI Skills are coming soon</p>
          <p className="mt-1 text-sm text-gray-500">Run custom prompts over this meeting, like a sales scorecard or objection finder.</p>
        </div>
      ) : (
        <article className="mx-auto max-w-3xl px-5 pb-16 pt-3 md:px-10">
          <h1 className="text-2xl font-normal leading-tight text-gray-900">{meeting.title}</h1>
          <div className="mt-3 flex flex-wrap items-center gap-x-2 gap-y-2 text-sm text-gray-500">
            <span className="font-medium text-gray-700 underline decoration-gray-300 underline-offset-4">{ownerName}</span>
            <span>{formatMeetingDate(meeting.started_at)}</span>
            <span aria-hidden>·</span>
            <span>{formatDuration(meeting.duration_ms)}</span>
            <span aria-hidden>·</span>
            <span>
              {meeting.participants.length} participant{meeting.participants.length === 1 ? "" : "s"}
            </span>
            <AvatarStack people={meeting.participants} max={5} size="sm" />
          </div>

          {keywords.length > 0 ? (
            <ul className="mt-4 flex flex-wrap gap-1.5" aria-label="Topics">
              {keywords.map((keyword) => (
                <li key={keyword}>
                  {/* A topic chip opens the library filtered to meetings that share this topic. */}
                  <Link
                    href={`/meetings?keyword=${encodeURIComponent(keyword)}`}
                    title={`Meetings about "${keyword}"`}
                    className="inline-block rounded bg-raised px-2 py-1 text-xs text-gray-700 ring-1 ring-line hover:text-brand-700 hover:ring-brand-300"
                  >
                    {keyword}
                  </Link>
                </li>
              ))}
            </ul>
          ) : null}

          <div className="mt-7 flex items-center gap-3">
            <span className="flex items-center gap-1.5 text-sm text-gray-500">
              <Sparkles className="size-4" /> General Summary
            </span>
            <button
              type="button"
              onClick={() =>
                void navigator.clipboard?.writeText(notesAsText(meeting)).then(() => toast.success("Notes copied"))
              }
              className="rounded p-1 text-gray-400 hover:bg-raised hover:text-gray-700"
              aria-label="Copy notes"
              title="Copy notes"
            >
              <Copy className="size-4" />
            </button>
            {source ? <span className="ml-auto text-xs text-gray-400">{source}</span> : null}
          </div>

          {summary ? (
            <>
              <Heading>Overview</Heading>
              <p className="text-[15px] leading-7 text-gray-800">{summary.overview}</p>
              {summary.notes.length > 0 ? (
                <>
                  <Heading>Notes</Heading>
                  <ul className="list-disc space-y-1.5 pl-5 text-[15px] leading-7 text-gray-800 marker:text-gray-400">
                    {summary.notes.map((note, index) => (
                      <li key={index}>{note}</li>
                    ))}
                  </ul>
                </>
              ) : null}
            </>
          ) : (
            <p className="mt-4 text-sm text-gray-500">No summary for this meeting.</p>
          )}

          {chapters.length > 0 ? <Outline chapters={chapters} activeIndex={activeChapterIndex} onSeek={onSeek} /> : null}

          <Heading>Action items</Heading>
          {actionItems}
        </article>
      )}
    </div>
  );
});

function Outline({ chapters, activeIndex, onSeek }: { chapters: Chapter[]; activeIndex: number; onSeek: (ms: number) => void }) {
  return (
    <>
      <Heading>Outline</Heading>
      <ol className="space-y-3">
        {chapters.map((chapter, index) => (
          <li
            key={chapter.id}
            aria-current={index === activeIndex ? "true" : undefined}
            className={clsx(
              "border-l-2 pl-3 transition-colors",
              index === activeIndex ? "border-brand-500" : "border-transparent",
            )}
          >
            <p className="text-[15px] font-medium text-gray-900">
              {chapter.title} <TimeLink ms={chapter.start_ms} onSeek={onSeek} />
            </p>
            {chapter.gist ? <p className="mt-0.5 text-[15px] leading-7 text-gray-700">{chapter.gist}</p> : null}
          </li>
        ))}
      </ol>
    </>
  );
}
